### ISSUE TITLE
request for none exists local html file will stuck pending

### ISSUE THREAD

**Issue by xjfnet** [chromelyapps/Chromely#254] opened 2020-10-26 09:27 UTC
i have chane the local resourse schema from 'local' to 'http'
```cs
new UrlScheme("resource", "local", string.Empty, string.Empty, UrlSchemeType.Resource, baseUrlStrict: false),
```
and then change url to a none exists local html file in the devtools console
```js
location.hef = 'local://app/not-exists.html';
```
then in the devtools networks, the request is pending and never finished

**Comment by xjfnet** [comment] 2020-10-26 10:04
'local' or 'http' both stuck pending

**Comment by mattkol** [comment] 2020-10-26 10:54
@xjfnet debugging devtools itself is not within scope for this project. I will suggest you do what you do first without devtools and then try with devtools.

Also you had: **'loca'**, do you mean:
````
location.hef = 'local://app/not-exists.html';
````

**Comment by xjfnet** [comment] 2020-10-26 11:40
if you set StartUrl = 'local://app/not-exists.html'; the page will be white, and the request is pending

**Comment by mattkol** [comment] 2020-10-26 11:59
Can you see the file "app/not-exists.htm" in the bin directory?
Does the [demo](https://github.com/chromelyapps/demo-projects/tree/master/regular-chromely/CrossPlatDemo) work with:
````
StartUrl ="local://app/index.html";
````
I do not think the "-" (dash) in **'non-exists.html'** will impact anything but you may want to check that too.

**Comment by xjfnet** [comment] 2020-10-26 13:14
```js
StartUrl = "local://app/index.html";
```
this works fine, then delete the index.html, the page is blank and the the request is pending for ever, but 404 or other error is expected

**Comment by mattkol** [comment] 2020-10-26 23:13
> pending for ever

I could not reproduce this. It should abort the request if file does not exist: 
https://github.com/chromelyapps/Chromely/blob/9b07200e0533d584c76ba4dbdf66132679ccb519/src/Chromely/Browser/Handlers/DefaultResourceSchemeHandler.cs#L61
Do you know where this is pending?

> but 404 or other error is expected

That is one way to look at it, so instead of aborting the call, we propagate an error code. That makes sense. If this is something you need, I will suggest you create a custom resource handler.  We can consider this feature for a future release.

**Comment by xjfnet** [comment] 2020-10-27 00:15
it seems that i post this at wrong place. sorry
i used Chromely.CefSharp
Chromely.CefSharp.Browser.DefaultResourceSchemeHandler just return CefReturnValue.ContinueAsync;

https://github.com/chromelyapps/CefSharp/blob/829bc03783ef85b89db48d624f8936c76dfc3649/src/Chromely.CefSharp/Browser/Handlers/DefaultResourceSchemeHandler.cs#L81

**Comment by mattkol** [comment] 2020-10-27 01:11
That is good.
Both should be fixed with right error code.
You can create default handler for either if this is something you need ASAP.
Thanks.

**Closed** 2020-11-07 11:54 UTC
