### ISSUE TITLE
Improper initial positioning of webview before resize

### ISSUE THREAD

**Issue by Fydar** [chromelyapps/Chromely#78] opened 2019-03-08 21:35 UTC
When a fullscreen `<div>` is used (archived either using `height: 100%; width: 100%;` or `width: 100vw; height: 100vh;`) it's initially positioned larger than the screen. Observe the below screenshot:

![059723112d729f4d6adfdf0560444676](https://user-images.githubusercontent.com/19309165/54056335-a865b780-41e7-11e9-889a-2ee97696fb55.png)

And after a slight resize to the window.

![91da8b657c1bcc7c84db71432fc26476](https://user-images.githubusercontent.com/19309165/54056340-ac91d500-41e7-11e9-9ca9-efee2e1c4672.png)

## Steps to Reproduce

1. Create a HTML element that spans the whole page.
2. Create a child element that anchored to the bottom of the element. This can be achieved in many ways, I found it easiest to use CSS Grid.
3. Launch the application.
4. Observe.
4. Upon resizing the window you should notice that the issue goes away.

## Setup

Using `Chromely.CefGlue.Winapi` Version `66.0.0`

**Comment by mattkol** [comment] 2019-03-09 20:10
I am in transit and may not be able to respond properly to issues for some days. 

I see you are referencing v66. Have you tried v68?

**Comment by Fydar** [comment] 2019-03-10 20:04
Reproduced with version `68.0.0.1`.

**Comment by mattkol** [comment] 2019-03-11 01:32
@Fydar my only quick guess from experience is that this is likely a timing issue. Looks like due to request/response controls are adjusted after UI is shown. But let us try troubleshoot. Can you please send me the html file without your data? Just the html file where the "fullscreen div" is defined.

I am in transit and I have limited access to internet, but hopefully by weekend I should be able to look at it closely.

**Comment by Fydar** [comment] 2019-03-11 17:50
I have uploaded the HTML and CSS necessary to reproduce the issue.

[App.zip](https://github.com/chromelyapps/Chromely/files/2953575/App.zip)

**Comment by mattkol** [comment] 2019-03-14 13:43
@Fydar I cannot reproduce what you described. Please see attached and let me know what I am missing.
[issue78.zip](https://github.com/chromelyapps/Chromely/files/2966662/issue78.zip)

**Comment by Fydar** [comment] 2019-03-14 21:02
I'm unable to run the project you have attached, I have unzipped it, ran `dotnet restore`, `dotnet build` and finally `dotnet run` and it seems to compile but never do anything upon being ran. Am I missing something? I tried doing `dotnet chromelycef.dll download v68 --cpu=x64 --dest="bin\Debug\netcoreapp2.1" but it resulted in: `No executable found matching command "dotnet-chromelycef.dll"`

**Comment by mattkol** [comment] 2019-03-14 21:09
@Fydar sorry that is .NET project. Not .NET Core.

**Comment by Fydar** [comment] 2019-03-14 21:24
Ah okay.

I ran the project just fine :) Don't know how I missed it. The bug didn't appear in it either.

Perhaps this is a .NET Core issue?

**Comment by mattkol** [comment] 2019-03-14 21:25
That will be interesting.

**Comment by FrankPfattheicher** [comment] 2019-03-15 15:46
Tryed this using
`dotnet publish -r win-x64 --self-contained`
Cannot reproduce issue.

**Closed** 2019-03-31 00:15 UTC
